### PR TITLE
Build mkl-service for newer MKL version

### PR DESCRIPTION
**Pull request by oleksandr-pavlyk**
Bump up build number to get mkl-service built against newer version of MKL

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by oleksandr-pavlyk** [comment]
@conda-forge-admin, please rerender

**Comment by oleksandr-pavlyk** [comment]
@conda-forge/core The conda smithy's linter denies my existence. Is there something I need to change in the recipe itself?

**Comment by beckermr** [comment]
@conda-forge-admin relint

**Comment by beckermr** [comment]
hmmmmmmmm. We switched to an anonymous API request internally and maybe they rate limited us?

**Comment by beckermr** [comment]
it appears it worked now - might have been a one-time thing - we'll watch it and if it keeps happening, we can add more hooks to help in smithy.

**Comment by beckermr** [comment]
And no the recipe is fine!

**Comment by isuruf** [comment]
> We switched to an anonymous API request internally and maybe they rate limited us?

Yeah, they rate limit for 60 requests per hour and is not enough for the linter.

**Comment by beckermr** [comment]
Ahhhh ok. I can push a fix that should work.

**Comment by oleksandr-pavlyk** [comment]
@conda-forge-admin please, rerender

**Comment by hmaarrfk** [comment]
I didn't migrate them together, sorry about that:

https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/6453

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Comment by hmaarrfk** [comment]
do you not build this for OSX?

**Comment by h-vetinari** [comment]
MKL dropped support for osx a while ago, see https://github.com/conda-forge/intel_repack-feedstock/issues/62

**Comment by oleksandr-pavlyk** [comment]
Closing this as superseded by gh-36

**Pull request closed without merging**
