### PR TITLE
Bump up version to 2.4.1

### PR DESCRIPTION
**Pull request by oleksandr-pavlyk**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by oleksandr-pavlyk** [comment]
@conda-forge-admin , please rerender

**Comment by oleksandr-pavlyk** [comment]
@conda-forge/core How can I only release this package for cpython? I am not sure why it is failing for __73_pypy

**Comment by oleksandr-pavlyk** [comment]
@conda-forge/core Should I just delete all `.ci_support/*.____73_pypy.yaml` files?

**Comment by h-vetinari** [comment]
This is https://github.com/pypy/pypy/issues/4885. You can either use `pytest <8`, or skip pypy temporarily:
```
build:
  # temporarily skipped until pypy 7.3.15 due to https://github.com/pypy/pypy/issues/4885
  skip: true  # [python_impl == "pypy"]
```

**Comment by oleksandr-pavlyk** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
